version: '3'

services:
  db:
    container_name: skill-recommendation-db
    image: postgres:12-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: skill-recommendation
